name: Nightly

on:
  pull_request:
    branches: ["main"]
    types: [synchronize, labeled, unlabeled]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  knative_test:
    name: E2E test
    if: | 
      contains(github.event.pull_request.labels.*.name, 'ok-to-test') &&
      !contains(github.event.pull_request.labels.*.name, 'skip-test')
    uses: ./.github/workflows/knative_test.yml
    secrets: inherit

