name: Nightly

on:
  pull_request:
    branches: ["main"]
    types: [synchronize, labeled, unlabeled]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
#  urunc-deploy:
#    name: Test urunc-deploy
#    if: | 
#      contains(github.event.pull_request.labels.*.name, 'ok-to-test') &&
#      !contains(github.event.pull_request.labels.*.name, 'skip-test')
#    uses: ./.github/workflows/urunc-deploy.yml
#    secrets: inherit
#
#  knative_test:
#    needs: [urunc-deploy]
#    name: Test Knative
#    if: | 
#      contains(github.event.pull_request.labels.*.name, 'ok-to-test') &&
#      !contains(github.event.pull_request.labels.*.name, 'skip-test')
#    uses: ./.github/workflows/knative_test.yml
#    secrets: inherit

  knative_test:
    #needs: [urunc-deploy]
    name: Test Knative
    if: | 
      contains(github.event.pull_request.labels.*.name, 'ok-to-test') &&
      !contains(github.event.pull_request.labels.*.name, 'skip-test')
    uses: ./.github/workflows/knative_test.yml
    secrets: inherit


